### ISSUE TITLE
unsolicited feedback

### ISSUE THREAD

**Issue by chadxz** [Silicon-Ally/rules_gqlgen#10]
Hi there 👋 

I was poking at this repository this evening because I've been wanting to get gqlgen working with Bazel for a while and stumbled across your project today.

When I was getting this setup in a fresh repository, I wasn't quite sure how to bootstrap a new application... specifically, how the server.go and corresponding resolvers get created when first starting a project.

Also, I think it may help to put the example in its own workspace. It would probably also help to expose a macro so that dependents could load the repository dependencies required by this rule. I prototyped this some this evening and mostly had it working, but I use IntelliJ for development and the bazel plugin for it was very confused about the nested workspaces. Still trying to figure out if it's a bug in the plugin or something else.

I'm still pretty enthusiastic about this rule though despite the rough edges. Nice work getting this far.

**Comment by bcspragu** [comment]
Thanks for the feedback, it's much appreciated! Addressing individually:

**Re: bootstrapping** - Agreed that bootstrapping could definitely be clearer, filed #11 to tackle the `example/WORKSPACE` part of that, and can add some additional docs to illustrate the current state of affairs.

**Re: macros** - Agreed that a `gqlgen_dependencies` macro makes sense here, I mostly just need to read up on how different versions of `go_repository` rules interact, because in this case, clients will also necessarily have their own `go_repository` rule for gqlgen (if they want to use it in a Go binary).

**Re: development plugin issues** - What kinds of IDE problems are you seeing, and what do you mean by 'nested workspaces'? Generally, every set of rules on imports (e.g. `io_bazel_rules_go`, `rules_gqlgen`) will have one root `WORKSPACE`, which is the case here.

More generally, I think the biggest thing `rules_gqlgen` needs is to pull dependencies directly from the existing Bazel environment, instead of building up its own Go modules system and downloading deps independently every time a `schema.graphql` file changes. I've come across other Go + Bazel rules that should also have to deal with this problem (like [sqlc](https://sqlc.dev/) and [rules_sqlc](https://github.com/plezentek/rules_sqlc)), but I haven't examined how they handle it. Filed #12 to take a look at it

**Comment by chadxzs** [comment]
The nesting I was referring to was where I was trying to add a WORKSPACE file in the examples directory of this repository, so that it would behave more like a stand alone application. I figure this is doable but I'm new to that and was having some trouble.

**Comment by bcspragu** [comment]
Ah makes sense, I've got a branch where I've got it mostly working, hoping to get that finished up today
